# المفتاح اللي كتبته في الخطوة اللي فاتت
sonar.projectKey=ecommerce-backend

# مسار الكود اللي هيتفحص (ممكن تحدد فولدرات معينة زي app و routes)
sonar.sources=app, routes, config, database

# استبعاد ملفات الـ Vendor والتست عشان مش محتاج تقيمها
sonar.exclusions=vendor/**, tests/**, node_modules/**, public/**

# رابط السيرفر
sonar.host.url=http://localhost:9002

# الـ Token اللي نسخته
sonar.login=YOUR_GENERATED_TOKEN